// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: pb/valid.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_valid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_valid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_pb_valid_proto_rawDescGZIP(), []int{0}
}

func (x *StringList) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

var file_pb_valid_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50000,
		Name:          "valid.required",
		Tag:           "varint,50000,opt,name=required",
		Filename:      "pb/valid.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50001,
		Name:          "valid.min",
		Tag:           "varint,50001,opt,name=min",
		Filename:      "pb/valid.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50002,
		Name:          "valid.max",
		Tag:           "varint,50002,opt,name=max",
		Filename:      "pb/valid.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50003,
		Name:          "valid.lmin",
		Tag:           "varint,50003,opt,name=lmin",
		Filename:      "pb/valid.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50004,
		Name:          "valid.lmax",
		Tag:           "varint,50004,opt,name=lmax",
		Filename:      "pb/valid.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*StringList)(nil),
		Field:         50005,
		Name:          "valid.allowed",
		Tag:           "bytes,50005,opt,name=allowed",
		Filename:      "pb/valid.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// optional bool required = 50000;
	E_Required = &file_pb_valid_proto_extTypes[0]
	// optional int32 min = 50001;
	E_Min = &file_pb_valid_proto_extTypes[1]
	// optional int32 max = 50002;
	E_Max = &file_pb_valid_proto_extTypes[2]
	// optional int32 lmin = 50003;
	E_Lmin = &file_pb_valid_proto_extTypes[3]
	// optional int32 lmax = 50004;
	E_Lmax = &file_pb_valid_proto_extTypes[4]
	// optional valid.StringList allowed = 50005;
	E_Allowed = &file_pb_valid_proto_extTypes[5]
)

var File_pb_valid_proto protoreflect.FileDescriptor

var file_pb_valid_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0a, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x3a, 0x3b, 0x0a, 0x08, 0x72,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x3a, 0x31, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x12,
	0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1,
	0x86, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x3a, 0x31, 0x0a, 0x03, 0x6d,
	0x61, 0x78, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xd2, 0x86, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x3a, 0x33,
	0x0a, 0x04, 0x6c, 0x6d, 0x69, 0x6e, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd3, 0x86, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c,
	0x6d, 0x69, 0x6e, 0x3a, 0x33, 0x0a, 0x04, 0x6c, 0x6d, 0x61, 0x78, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd4, 0x86, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6c, 0x6d, 0x61, 0x78, 0x3a, 0x4c, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xd5, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_valid_proto_rawDescOnce sync.Once
	file_pb_valid_proto_rawDescData = file_pb_valid_proto_rawDesc
)

func file_pb_valid_proto_rawDescGZIP() []byte {
	file_pb_valid_proto_rawDescOnce.Do(func() {
		file_pb_valid_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_valid_proto_rawDescData)
	})
	return file_pb_valid_proto_rawDescData
}

var file_pb_valid_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_valid_proto_goTypes = []interface{}{
	(*StringList)(nil),              // 0: valid.StringList
	(*descriptor.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_pb_valid_proto_depIdxs = []int32{
	1, // 0: valid.required:extendee -> google.protobuf.FieldOptions
	1, // 1: valid.min:extendee -> google.protobuf.FieldOptions
	1, // 2: valid.max:extendee -> google.protobuf.FieldOptions
	1, // 3: valid.lmin:extendee -> google.protobuf.FieldOptions
	1, // 4: valid.lmax:extendee -> google.protobuf.FieldOptions
	1, // 5: valid.allowed:extendee -> google.protobuf.FieldOptions
	0, // 6: valid.allowed:type_name -> valid.StringList
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	6, // [6:7] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_valid_proto_init() }
func file_pb_valid_proto_init() {
	if File_pb_valid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_valid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_valid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_pb_valid_proto_goTypes,
		DependencyIndexes: file_pb_valid_proto_depIdxs,
		MessageInfos:      file_pb_valid_proto_msgTypes,
		ExtensionInfos:    file_pb_valid_proto_extTypes,
	}.Build()
	File_pb_valid_proto = out.File
	file_pb_valid_proto_rawDesc = nil
	file_pb_valid_proto_goTypes = nil
	file_pb_valid_proto_depIdxs = nil
}
