name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go mod tidy
        go get github.com/google/wire/cmd/wire

    - name: Build
      run: |
        wire gen -output_file_prefix main- cmd/main.go
        go build cmd/main-wire_gen.go
        

    - name: Test
      run: |
        go generate test/test.go
        go test test/sample_test.go test/wire_gen.go
